### ISSUE TITLE
bug: IonDateTime doesn't work with Capacitor 3.0.0-rc.0

### ISSUE THREAD

**Issue by mirkonasato** [ionic-team/capacitor#4324]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 3.0.0-rc.0
  @capacitor/android: 3.0.0-rc.0
  @capacitor/cli: 3.0.0-rc.0

[success] Android looking great! 👌
```

### Platform(s)

Android (at least, I haven't tested it in iOS)

### Current Behavior

Tapping the `IonDateTime` field opens the date selector, however it's impossible to scroll to a different date. The date selector is frozen and does not respond to user input.

There's an error in the JavaScript console saying
```
TypeError: t.Capacitor.isPluginAvailable is not a function
```

### Expected Behavior

It should be possible to select a date, like in the [ion-datetime](https://ionicframework.com/docs/api/datetime) demo and like it works with Capacitor v2.

### Code Reproduction

Here's a simple Ionic React project that displays an `IonDateTime`, created with the Ionic CLI and upgraded to Capacitor v3 including the `app`, `haptics` and `keyboard` plugins as per [migration instructions](https://capacitorjs.com/docs/v3/updating/3-0#migrating-your-app-to-use-the-new-official-plugin-packages):

https://github.com/mirkonasato/iondatetime-cap3

### Other Technical Details

`npm --version` output: `6.14.11`

`node --version` output: `v14.16.0`

`pod --version` output (iOS issues only):

### Additional Context

Opening the issue here in the Capacitor project and not in the Ionic Framework one as I'm guessing it's not intentional to have Capacitor v3 break some current Ionic Framework functionality.

If the breaking change is intentional then at least it should be mentioned in the [v3 upgrade page](https://capacitorjs.com/docs/v3/updating/3-0).

**Comment by mirkonasato** [comment]
Ok, I found that it works fine if you explicitly [import @capacitor/core](https://capacitorjs.com/docs/v3/updating/3-0#importing-capacitorcore) as suggested in the update page.

If that's how it's supposed to work I would suggest changing the migration instructions to say that it's not simply a "good idea" but in fact a requirement.

**Comment by mirkonasato** [comment]
Closing as adding `import '@capacitor/core';` is also mentioned in the [Installing Capacitor](https://capacitorjs.com/docs/v3/getting-started#adding-capacitor-to-your-app) page so it must be by design.
