### ISSUE TITLE
bug: Cant compile iOS after update to 2.0.1

### ISSUE THREAD

**Issue by lucasrleandro** [ionic-team/capacitor#2778]
# Bug Report

## Capacitor Version
2.0.1

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
When I try to run my iOS project in XCODE i get the message: Use of unresolved identifier 'TmpViewController'. And in console: NSForwarding: warning: object 0x7fff89115030 of class 'PFEmbeddedMulticasterImplementation' does not implement doesNotRecognizeSelector: -- abort

## Expected Behavior
It should compile normally

## Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
Make sure your Podfile has this line
https://github.com/ionic-team/capacitor/blob/master/ios-template/App/Podfile#L7
That prevents Xcode from caching local pods, that’s what happening in your project, some of the classes are cached.

You can also do Project -> Clean Build Folder
