### ISSUE TITLE
bug: Error open app after build on iOS with xcode 11.4

### ISSUE THREAD

**Issue by SSuarezBrooktec** [ionic-team/capacitor#2638]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

Latest Dependencies:

  @capacitor/cli: 1.5.1

  @capacitor/core: 1.5.1

  @capacitor/android: 1.5.1

  @capacitor/ios: 1.5.1

Installed Dependencies:

  @capacitor/cli 1.5.1

  @capacitor/android 1.5.1

  @capacitor/core 1.5.1

  @capacitor/ios 1.5.1

## Affected Platform(s)

- [ ] Android
- [ X] iOS
- [ ] Electron
- [ ] Web

## Reproduction Steps

Compiling app on iOS

## Other Technical Details

`npm --version` output: 6.13.7
`node --version` output: v13.0.1
`pod --version` output (iOS issues only): 1.9.1

## Other Information

<img width="1005" alt="Captura de pantalla 2020-03-25 a las 20 16 47" src="https://user-images.githubusercontent.com/56263935/77576502-9b406700-6ed5-11ea-8a06-5cd455145325.png">

 ***** NSForwarding: warning: object 0x7fff89115030 of class 'PFEmbeddedMulticasterImplementation' does not implement methodSignatureForSelector: -- trouble ahead

 *** NSForwarding: warning: object 0x7fff89115030 of class 'PFEmbeddedMulticasterImplementation' does not implement doesNotRecognizeSelector: -- abort**

**Comment by SSuarezBrooktec** [comment]
Capacitor 2 beta could fix it?

**Comment by thmclellan** [comment]
Looks like a duplicate of https://github.com/ionic-team/capacitor/issues/2532. Updating to  @capacitor/ios@next worked for me on Xcode 11.4 on Catalina.

**Comment by SSuarezBrooktec** [comment]
Thanks @thmclellan
