### PR TITLE
fix(ios): avoid crash on registerPlugins on Xcode 11.4

### PR DESCRIPTION
**Pull request by jcesarmobile**
In Xcode 11.4 beta, Capacitor apps crash with

> NSForwarding: warning: object 0x1d64f3b70 of class 'PFEmbeddedMulticasterImplementation' does not implement methodSignatureForSelector: -- trouble ahead
> NSForwarding: warning: object 0x1d64f3b70 of class 'PFEmbeddedMulticasterImplementation' does not implement doesNotRecognizeSelector: -- abort

Do not merge yet in case Apple fix it in a future release, but have the change around just in ase

### CODE REVIEW

**Comment by jcesarmobile** [comment]
Going to merge since the first 11.4 beta was released a month ago and it's still broken on beta 3.
The changes keep working on Xcode 11.0, so should be harmless.

Closes #2532

**Comment by Taylorsuk** [comment]
I can confirm that the Version 11.4 (11E146) prod release has this issue too. Is it possible to include this in 1.5.2?

**Comment by shanoinsano10** [comment]
Just updated to xcode 11E146 and observing the same thing.

**Comment by jcesarmobile** [comment]
use `@capacitor/ios@next`
