### ISSUE TITLE
bug: Didn't find class "android.webkit.RenderProcessGoneDetail" with Android API 25

### ISSUE THREAD

**Issue by dengbin** [ionic-team/capacitor#5895]
## Bug Report
WebView cannot work in Android 7.1 API 25

### Capacitor Version
   "@capacitor/android": "^4.1.0",
    "@capacitor/app": "^4.0.1",
    "@capacitor/camera": "^4.1.0",
    "@capacitor/core": "^4.1.0",

variables.gradle：
    minSdkVersion = 22
    compileSdkVersion = 32
    targetSdkVersion = 32
    androidxActivityVersion = '1.4.0'
    androidxAppCompatVersion = '1.4.2'
    androidxCoordinatorLayoutVersion = '1.2.0'
    androidxCoreVersion = '1.8.0'
    androidxFragmentVersion = '1.4.1'
    junitVersion = '4.13.2'
    androidxJunitVersion = '1.1.3'
    androidxEspressoCoreVersion = '3.4.0'
    cordovaAndroidVersion = '10.1.1'
    androidxExifInterfaceVersion = '1.3.2'
    androidxMaterialVersion = '1.3.0'
    coreSplashScreenVersion = '1.0.0-rc01'
    androidxWebkitVersion = '1.4.0'
```
PASTE OUTPUT HERE
```
 [INFO:library_loader_hooks.cc(36)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_LibraryLoader: Expected native library version number "63.0.3239.111", actual native library version number "63.0.3239.111"
I/cr_BrowserStartup: Initializing chromium process, singleProcess=true
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$6>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/RenderProcessGoneDetail;
I/art:     at com.android.webview.chromium.WebViewContentsClientAdapter com.android.webview.chromium.WebViewChromiumFactoryProvider.createWebViewContentsClientAdapter(android.webkit.WebView, android.content.Context) (WebViewChromiumFactoryProvider.java:330)
I/art:     at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (WebViewChromium.java:42)
I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:692)
I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:627)
I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:610)
I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:597)
I/art:     at void com.getcapacitor.CapacitorWebView.<init>(android.content.Context, android.util.AttributeSet) (CapacitorWebView.java:16)
I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance0!(java.lang.Object[]) (Constructor.java:-2)
I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance(java.lang.Object[]) (Constructor.java:430)
I/art:     at android.view.View android.view.LayoutInflater.createView(java.lang.String, java.lang.String, android.util.AttributeSet) (LayoutInflater.java:645)
I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:787)
I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet) (LayoutInflater.java:727)
I/art:     at void android.view.LayoutInflater.rInflate(org.xmlpull.v1.XmlPullParser, android.view.View, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:858)
I/art:     at void android.view.LayoutInflater.rInflateChildren(org.xmlpull.v1.XmlPullParser, android.view.View, android.util.AttributeSet, boolean) (LayoutInflater.java:821)
I/art:     at android.view.View android.view.LayoutInflater.inflate(org.xmlpull.v1.XmlPullParser, android.view.ViewGroup, boolean) (LayoutInflater.java:518)
I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup, boolean) (LayoutInflater.java:426)
I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup) (LayoutInflater.java:377)
I/art:     at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:706)
I/art:     at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:195)
I/art:     at void com.getcapacitor.BridgeActivity.onCreate(android.os.Bundle) (BridgeActivity.java:28)
I/art:     at void com.breakany.ferryman.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:66)
I/art:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6681)
I/art:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1118)
I/art:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2696)
I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2808)
I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1544)
I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:110)
I/art:     at void android.os.Looper.loop() (Looper.java:203)
I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6293)
I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1084)
I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:945)
I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.RenderProcessGoneDetail" on path: DexPathList[[zip file "/system/app/WebViewGoogle/WebViewGoogle.apk"],nativeLibraryDirectories=[/system/app/WebViewGoogle/lib/arm64, /system/app/WebViewGoogle/WebViewGoogle.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]
I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/art:     at com.android.webview.chromium.WebViewContentsClientAdapter com.android.webview.chromium.WebViewChromiumFactoryProvider.createWebViewContentsClientAdapter(android.webkit.WebView, android.content.Context) (WebViewChromiumFactoryProvider.java:330)
I/art:     at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (WebViewChromium.java:42)
I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:692)
I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:627)
I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:610)
I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:597)
I/art:     at void com.getcapacitor.CapacitorWebView.<init>(android.content.Context, android.util.AttributeSet) (CapacitorWebView.java:16)
I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance0!(java.lang.Object[]) (Constructor.java:-2)
I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance(java.lang.Object[]) (Constructor.java:430)
I/art:     at android.view.View android.view.LayoutInflater.createView(java.lang.String, java.lang.String, android.util.AttributeSet) (LayoutInflater.java:645)
I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:787)
I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet) (LayoutInflater.java:727)
I/art:     at void android.view.LayoutInflater.rInflate(org.xmlpull.v1.XmlPullParser, android.view.View, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:858)
I/art:     at void android.view.LayoutInflater.rInflateChildren(org.xmlpull.v1.XmlPullParser, android.view.View, android.util.AttributeSet, boolean) (LayoutInflater.java:821)
I/art:     at android.view.View android.view.LayoutInflater.inflate(org.xmlpull.v1.XmlPullParser, android.view.ViewGroup, boolean) (LayoutInflater.java:518)
I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup, boolean) (LayoutInflater.java:426)
I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup) (LayoutInflater.java:377)
I/art:     at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:706)
I/art:     at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:195)
I/art:     at void com.getcapacitor.BridgeActivity.onCreate(android.os.Bundle) (BridgeActivity.java:28)
I/art:     at void com.breakany.ferryman.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:66)
I/art:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6681)
I/art:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1118)
I/art:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2696)
I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2808)
I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1544)
I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:110)
I/art:     at void android.os.Looper.loop() (Looper.java:203)
I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6293)
I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1084)
I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:945)
I/art: 
D/MPlugin: com.mediatek.common.telephony.IOnlyOwnerSimSupportClazz exists on mapping table : false
E/MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
D/Capacitor: Starting BridgeActivity
E/chromium: [ERROR:devtools_http_handler.cc(249)] Cannot start http server for devtools. Stop devtools.
D/WebView: addJavascriptInterface=androidBridge
D/Capacitor: Registering plugin: WebView
D/Capacitor: Registering plugin: App
D/Capacitor: Registering plugin: Camera
D/Capacitor: Registering plugin: Haptics
D/Capacitor: Registering plugin: Keyboard
D/Capacitor: Registering plugin: Network
D/Capacitor: Registering plugin: SplashScreen
D/Capacitor: Registering plugin: StatusBar
D/Capacitor: Loading app at http://localhost
W/Capacitor: Unable to get package info for 'com.google.android.webview'android.content.pm.PackageManager$NameNotFoundException: com.android.chrome
W/Capacitor: Unable to get package info for 'com.android.webview'android.content.pm.PackageManager$NameNotFoundException: com.android.webview
E/Capacitor: System WebView is not supported
### Platform(s)

Android 7.1 API 25

### Current Behavior
Unable to load and display index.html normally

### Other Technical Details
but,It works normally in previous versions, as follows:

    "@capacitor/android": "^3.1.1",
    "@capacitor/app": "^1.0.2",
    "@capacitor/camera": "^1.0.3",
    "@capacitor/core": "^3.2.0",
    "@capacitor/ios": "^3.1.1",
    "@capacitor/network": "^1.0.2",
    "@capacitor/splash-screen": "^1.0.2",

    minSdkVersion = 21
    compileSdkVersion = 28
    targetSdkVersion = 28
    androidxActivityVersion = '1.2.0'
    androidxAppCompatVersion = '1.2.0'
    androidxCoordinatorLayoutVersion = '1.1.0'
    androidxCoreVersion = '1.3.2'
    androidxFragmentVersion = '1.3.0'
    junitVersion = '4.13.1'
    androidxJunitVersion = '1.1.2'
    androidxEspressoCoreVersion = '3.3.0'
    cordovaAndroidVersion = '7.0.0'
    androidxExifInterfaceVersion = '1.3.2'
    androidxMaterialVersion = '1.3.0'
}

 It is reasonable that chrome 60 or above can work normally. Check that my version is 63. Why is this situation? Are there other people who encounter this situation and how to solve it?

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by dengbin** [comment]
Even if the operation is completely based on the official example, the same error will be reported.
This means that this has nothing to do with ionic code.
At the same time, I did not modify any of the codes, so I got such an error.

**Comment by jcesarmobile** [comment]
We need a sample app for being able to reproduce. If we can't reproduce we can't fix it.
Please, provide a sample app where the issue can be reproduced.

**Comment by dengbin** [comment]
I think it should be because my android version is 7.1. The commands I use are as follows:
1、ionic start myApp tabs
2、npm i @capacitor/core.   npm i -D @capacitor/cli
3、npm i @capacitor/android 
4、npx cap add android
5、npx cap sync
6.  npx cap open android  


 There's nothing else

**Comment by dengbin** [comment]
Under the supplementary note, the same equipment is normal in V3, and such an error will occur only when upgrading to v4.

**Comment by jcesarmobile** [comment]
please, can you provide the sample app you got when doing those steps?
There is no enough information to reproduce, we can't know the ionic CLI version nor the framework you choose on ionic start command

**Comment by dengbin** [comment]
angular
The error log shows 63 +, but I am http://liulanmi.com/labs/core.html Is it because the chrome kernel is less than 60?
thanks！

**Comment by dengbin** [comment]
angular
The error log shows chrome core is  63 +, 
But I found that on the website（ http://liulanmi.com/labs/core.html ）It is 53 + and less than 60. Is this the reason?

**Comment by jcesarmobile** [comment]
Angular by default only supports latest 2 android versions, you can change the build options to support es5.
