### ISSUE TITLE
[Bug]: Capacitor is undefined, Capacitor.triggerEvent is not a function in allowNavigation routes

### ISSUE THREAD

**Issue by fmorett** [ionic-team/capacitor#7957]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 7.2.0
  @capacitor/core: 7.2.0
  @capacitor/android: 7.2.0
  @capacitor/ios: 7.2.0

Installed Dependencies:

  @capacitor/cli: 7.2.0
  @capacitor/core: 7.2.0
  @capacitor/android: 7.2.0
  @capacitor/ios: 7.2.0

### Other API Details

```Shell

```

### Platforms Affected

- [ ] iOS
- [x] Android
- [ ] Web

### Current Behavior

TypeError: window.Capacitor.triggerEvent is not a function. (that was the error i have been seeing in react)
In the reproduction example straight up window.Capacitor is not defined.

I see this error after navigating to a different domain, that is whitelisted for allowNavigation.

In the main route (localhost) it works.

Also Capacitor tells its a native platform and correctly returns android as platform.( in react, in the reproduction its undefined)

### Expected Behavior

Capacitor should be defined.

### Project Reproduction

https://github.com/fmorett/capacitor-bug1-repro

**Comment by fmorett** [comment]
Also as a side info, everything worked fine in my app until i upgraded to capacitor 7 from cap 5.

**Comment by fmorett** [comment]
So upon further investigation, it seems to work in @capacitor/android@5.7.8 and is broken in @capacitor/android@6.0.0

**Comment by fmorett** [comment]
Why has this been closed???
